<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select perusahaan</name>
   <tag></tag>
   <elementGuidId>0ee9a95b-ffa5-4695-90aa-dde399acf72f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-t8da-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-t8da-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>520cb941-dffb-4889-a77a-cfa9c01483e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>7397963e-4314-4710-9c1f-ac0c85ec5531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-t8da-container</value>
      <webElementGuid>25d717ae-44b6-4c81-b8a6-696546bf5aad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Select perusahaan</value>
      <webElementGuid>5c577243-88d1-4b79-a78d-caed5280b99a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select perusahaan</value>
      <webElementGuid>3f717c62-b159-4dfd-8288-3b9b982dcab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-t8da-container&quot;)</value>
      <webElementGuid>3253d33c-c04b-4aa0-aaef-21ee2be63312</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-t8da-container']</value>
      <webElementGuid>ce258d58-7b96-4738-bbef-973ad834496e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>09481505-6887-4355-98df-a4e7fc6dbb7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-t8da-container' and @title = 'Select perusahaan' and (text() = 'Select perusahaan' or . = 'Select perusahaan')]</value>
      <webElementGuid>1ee815ed-8ad8-4b1d-972d-34aa2e96bacd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
