<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Lanjut</name>
   <tag></tag>
   <elementGuidId>4078385d-9442-4cc6-9934-61c5cee14c6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-lanjut']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-lanjut</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>646354fa-24b0-4100-8dd5-de48ba3a1ec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>efd3ffa2-f2e2-44d0-83a6-a2a0b7c592bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary waves-effect waves-light pull-right</value>
      <webElementGuid>063148e3-4b65-4c18-8eb9-3e13d1b0fc37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-lanjut</value>
      <webElementGuid>b62cbc73-d0ca-4cc9-a38d-2c0c4da21ced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lanjut </value>
      <webElementGuid>52ececed-0958-4cd9-9dab-7df82396efb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-lanjut&quot;)</value>
      <webElementGuid>5cb90cbe-46c4-41f9-91fa-5db7cb5d0ec7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-lanjut']</value>
      <webElementGuid>b5b1c710-9cfb-47a0-bb1f-3b91354b8f2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='default-wizard']/fieldset/button</value>
      <webElementGuid>f1c88b73-056f-463d-86f3-58e9656a84d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/button</value>
      <webElementGuid>5fb73861-d89d-4b63-b2d6-aa558e02fc88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btn-lanjut' and (text() = 'Lanjut ' or . = 'Lanjut ')]</value>
      <webElementGuid>5a68fa7e-1851-45b0-a78b-48d899d5ca9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
