<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tambah Periode Pelaporan</name>
   <tag></tag>
   <elementGuidId>300581d2-79e4-44d6-bad9-9a0fa2135664</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-tambah-data']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-tambah-data</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>33395f11-0d62-450c-804f-354bdf5ebddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>875b0eb2-7ccb-4e48-afae-bb3a6e63418b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default waves-effect waves-light pull-left input-sm</value>
      <webElementGuid>f444c0cd-67b4-400e-ab36-32cb6fd9af3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-tambah-data</value>
      <webElementGuid>fb56fbaa-9533-4498-ae72-b8857944a241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Tambah Periode Pelaporan</value>
      <webElementGuid>a27a22d1-396f-4246-ac6c-61aac6752b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-tambah-data&quot;)</value>
      <webElementGuid>175471b1-c85a-4622-bde1-cd919b085a66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-tambah-data']</value>
      <webElementGuid>d0020d83-b6ff-4995-9209-8084bafc1f12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[3]/div/div/div[3]/div/div/div/div/button</value>
      <webElementGuid>4aa6cf4c-6ef2-41fa-9419-9503d0604933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>3e0d6e87-a8cc-4e93-9609-566f66404371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btn-tambah-data' and (text() = ' Tambah Periode Pelaporan' or . = ' Tambah Periode Pelaporan')]</value>
      <webElementGuid>7ca04a01-3e56-4677-8964-f65fc614f395</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
