<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_alamat</name>
   <tag></tag>
   <elementGuidId>4f4bcadc-7e18-4684-b7dc-2a3d17173563</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='alamat']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#alamat</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>87fd18d4-cfa5-4e49-862a-6e635d7d360b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e7af69ee-14e6-4e99-914f-e3adbe72dbe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>alamat</value>
      <webElementGuid>a688d570-2717-4939-a380-54b3f9887d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>alamat</value>
      <webElementGuid>b1534134-a152-4707-915e-d6006beb59c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text</value>
      <webElementGuid>c000cb91-3b06-4ecb-8a7d-2e8d1d6b1ecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>validateAlamat(this)</value>
      <webElementGuid>465511be-41ad-4e76-ab4f-79f4ee6f9396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alamat&quot;)</value>
      <webElementGuid>3d1c1931-8aa6-488b-a672-3be7cae5b22f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='alamat']</value>
      <webElementGuid>677a89dc-a6fe-420e-a62c-051d4113d7ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='default-wizard']/fieldset/div/div[2]/div[5]/input</value>
      <webElementGuid>709e87d5-a8ec-42fd-ac01-7fd7b090f549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[5]/input</value>
      <webElementGuid>4a90f9d7-ddf1-4db3-a4e3-e8da9f14dacb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'alamat' and @name = 'alamat']</value>
      <webElementGuid>766ca4f5-2f5d-4223-94cb-de4c6150927a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
