<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_tgl_awal_kontrak</name>
   <tag></tag>
   <elementGuidId>efe8ce0a-d0b9-47d4-8425-aa606cc4f13c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tgl_awal_kontrak']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tgl_awal_kontrak</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>16c05187-8891-4ac8-bd1a-b58c90e1b495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tgl_awal_kontrak</value>
      <webElementGuid>79744dad-ab50-4b60-a054-8edd7bce762f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tgl_awal_kontrak</value>
      <webElementGuid>64f8cdea-b256-44ac-873c-a194be41a3e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d6919f88-72e5-4111-bae6-d174e9d940f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>194cadc0-1130-4ec5-a364-c2910662a607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd-mm-yyyy</value>
      <webElementGuid>a7fe8040-e1f5-420d-b5af-255a9c1fad49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>changeDate()</value>
      <webElementGuid>4abf70ba-f721-4b86-bf3d-c116354eecac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tgl_awal_kontrak&quot;)</value>
      <webElementGuid>2cf2f19b-55f3-43fb-ab54-7c341b5b93ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tgl_awal_kontrak']</value>
      <webElementGuid>b7b29c89-813b-4f94-8496-6982c60c196b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='default-wizard']/fieldset/div/div[2]/div[2]/div/div/input</value>
      <webElementGuid>e7cc1213-4a6c-44da-b179-3fa2fae1a718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>5ba78786-9ee0-4712-a2da-d8cdfcd00c71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tgl_awal_kontrak' and @name = 'tgl_awal_kontrak' and @type = 'text' and @placeholder = 'dd-mm-yyyy']</value>
      <webElementGuid>a98c6427-2a69-4ce5-8ac0-bc8d35518524</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
