<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_tgl_akhir_kontrak</name>
   <tag></tag>
   <elementGuidId>c1298515-1576-427d-87b7-b923fc5a317c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tgl_akhir_kontrak']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tgl_akhir_kontrak</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a38f3744-2f33-4336-abb1-4c6b01e4c3e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tgl_akhir_kontrak</value>
      <webElementGuid>677dce4b-ac8d-4a99-9d87-fb03f7e39f6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tgl_akhir_kontrak</value>
      <webElementGuid>644267c7-097d-4eb8-8120-d067fafbc59b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bcc8ba99-5a10-47aa-990e-1fe7de974d95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>cb2c3488-35bf-469f-a29a-9bf3f0683334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd-mm-yyyy</value>
      <webElementGuid>8d7b3e5f-fd5a-44e6-8a84-c9680a3e6024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>changeDate()</value>
      <webElementGuid>56d6d41c-087c-4eab-a4e9-6005792423e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>52c3844d-b1b3-45bb-8755-736ecba9c255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tgl_akhir_kontrak&quot;)</value>
      <webElementGuid>3b020b3b-7378-45c0-bcaf-a9596ee6a9af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tgl_akhir_kontrak']</value>
      <webElementGuid>1ebb68d9-53b4-4d5b-9ba8-358840ba07bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='default-wizard']/fieldset/div/div[2]/div[2]/div[2]/div/input</value>
      <webElementGuid>162bb845-320b-476a-85c6-6aa44d17b1b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>cfd81f09-8e9f-419c-a191-d0725ee6953a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tgl_akhir_kontrak' and @name = 'tgl_akhir_kontrak' and @type = 'text' and @placeholder = 'dd-mm-yyyy']</value>
      <webElementGuid>5af370d8-753e-451e-85c5-92900001d750</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
