<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_upah</name>
   <tag></tag>
   <elementGuidId>24f9dc74-c7b5-4944-a785-208628639db4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='upah']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#upah</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>140b00f2-e59e-4ff8-ba0a-e7053c63ae0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8970a81e-52cf-409c-8cd6-87fea7de4818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>upah</value>
      <webElementGuid>6ed57d68-4fe8-4a22-8e3d-dc1125d6d6a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>upah</value>
      <webElementGuid>a48c5cef-ab12-4d4e-abed-187d2075198e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control autonumber</value>
      <webElementGuid>87389c70-c101-4cbd-9059-a393cd313baf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-a-sep</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>af852063-64a6-41e6-841c-92e6a7400b92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-a-dec</name>
      <type>Main</type>
      <value>,</value>
      <webElementGuid>cf53949c-b69d-4992-83b6-6b1f5e123a81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;upah&quot;)</value>
      <webElementGuid>9690a39e-bc53-46a3-a71d-3666e680180a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='upah']</value>
      <webElementGuid>57945dbb-0eb9-47cb-b4f7-53f3b09b7179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='default-wizard']/fieldset/div/div[2]/div[4]/input</value>
      <webElementGuid>153a856a-1976-49ab-969b-2296faa8d80e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/input</value>
      <webElementGuid>cc63ffbf-3a10-4cf0-b700-e4cef0a6a7ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'upah' and @name = 'upah']</value>
      <webElementGuid>eb367087-d1cd-467b-812b-7e94bad66193</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
