<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_i_nama_lengkap</name>
   <tag></tag>
   <elementGuidId>54aa3704-fdb1-434c-ac0b-556658102f0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='i_nama_lengkap']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#i_nama_lengkap</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c0f6bd6f-c5ac-4a72-b8f7-81ae64af5e66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3b59e09a-ed95-45a8-94ca-a5eb3a80a44f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>i_nama_lengkap</value>
      <webElementGuid>fec5e76b-021c-437c-a15f-c7431925b0c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>i_nama_lengkap</value>
      <webElementGuid>3cd16eaa-3d93-4a82-932c-2fa664acfe74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control required</value>
      <webElementGuid>9216defb-eba1-495c-9cf6-217307a45e14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama Sesuai e-KTP</value>
      <webElementGuid>99003fd0-96c6-4470-a816-2690f2a57c6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>validateNama(this)</value>
      <webElementGuid>c61cfbd9-b070-454d-b4c0-d7a253ca55e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i_nama_lengkap&quot;)</value>
      <webElementGuid>4569dbb0-3085-4a2a-afa8-271104e2dda7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='i_nama_lengkap']</value>
      <webElementGuid>0e1035a3-89b6-43a1-9a42-d8ba4f80cdc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_1']/div/div[2]/div/input</value>
      <webElementGuid>bf889c2c-3d8b-4fa9-84f5-3aea8ccb85e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>e59bd3cc-7193-427b-a8af-7fec73cbf361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'i_nama_lengkap' and @id = 'i_nama_lengkap' and @placeholder = 'Nama Sesuai e-KTP']</value>
      <webElementGuid>8414c624-9f54-468a-a58f-464f777f8129</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
