<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_nomor_pegawai</name>
   <tag></tag>
   <elementGuidId>d4d781e9-eb98-4820-9978-78c4de9e2887</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='nomor_pegawai']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nomor_pegawai</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>41cead27-bee2-4aaf-a21c-a39b6c87fe72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>nomor_pegawai>Nomor Pegawai :&lt;/label>
                                        &lt;input type=</value>
      <webElementGuid>9d4d869d-43fc-456c-91de-f89e4af99a08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nomor_pegawai</value>
      <webElementGuid>31dc2ad3-41f4-4268-89f9-9ce63398cddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nomor_pegawai</value>
      <webElementGuid>2edec19e-4be8-4524-aff9-54321bff4041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>938a3284-9b75-4155-b020-8896ad70ccbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>validateAlphanum(this)</value>
      <webElementGuid>6b947a4a-0822-4fd5-89aa-8e90a3c58ddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nomor_pegawai&quot;)</value>
      <webElementGuid>139e87a0-0a23-49bd-af84-ca036b588898</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='nomor_pegawai']</value>
      <webElementGuid>33a7584e-78cd-49a6-9dfe-9c47d9ac21c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='default-wizard']/fieldset/div/div[2]/div[3]/label</value>
      <webElementGuid>8e57a7a2-1385-4a7d-94d4-aa133702b0a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/label</value>
      <webElementGuid>cf8aae14-8596-4bc7-9fee-48b674aa0a30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'nomor_pegawai' and @name = 'nomor_pegawai']</value>
      <webElementGuid>ec2622e7-c97e-4b65-ab06-25fe5ffd8404</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
