<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-Pilih-                             _82f089</name>
   <tag></tag>
   <elementGuidId>bfaa9046-9f5e-4903-95c5-a2c91732316d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='status_pkwt']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#status_pkwt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>16d57765-eaf8-4c91-ab38-ddd46d13093e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>status_pkwt</value>
      <webElementGuid>722dfa60-d592-4b0c-9df8-8e74ef938d45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1f9ae787-3bbd-40f8-acba-4437ffecb4fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>status_pkwt</value>
      <webElementGuid>b8df4895-ce93-43f3-baee-c9384802fb92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>getCombo(this)</value>
      <webElementGuid>f79788ad-9d3f-47ae-9a09-ab60a1474fc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                           -Pilih-
                                           PKWT (Perjanjian Kerja Waktu Tertentu)
                                           PKWTT (Perjanjian Kerja Waktu Tidak Tertentu)
                                         </value>
      <webElementGuid>42dcfe67-3b51-4e82-a0e0-2da7734612b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;status_pkwt&quot;)</value>
      <webElementGuid>d08be75e-f5ec-482a-b9de-bd6c9b2515b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='status_pkwt']</value>
      <webElementGuid>9781a2f4-e500-4357-99a2-a8db4f942645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='default-wizard']/fieldset/div/div[2]/div/select</value>
      <webElementGuid>3d8a0c40-d814-4673-9798-c9132639fe67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>f27a9069-3407-4d6d-b821-de00267cc4c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'status_pkwt' and @id = 'status_pkwt' and (text() = '
                                           -Pilih-
                                           PKWT (Perjanjian Kerja Waktu Tertentu)
                                           PKWTT (Perjanjian Kerja Waktu Tidak Tertentu)
                                         ' or . = '
                                           -Pilih-
                                           PKWT (Perjanjian Kerja Waktu Tertentu)
                                           PKWTT (Perjanjian Kerja Waktu Tidak Tertentu)
                                         ')]</value>
      <webElementGuid>dffd38f5-bbbb-44e0-a5fc-2e63f3cfb800</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
