<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-Pilih-                             _d74a24</name>
   <tag></tag>
   <elementGuidId>c535461e-9c11-4c84-8602-a6ee1b8326e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='jenis_kelamin']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jenis_kelamin</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bcb015cb-52bf-4705-92bb-b9cb3d320b8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jenis_kelamin</value>
      <webElementGuid>436c74d5-deb6-4ed3-8784-9d3e5ebaa3a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>09f2b935-3a6e-41e5-949b-a34a2876eb21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jenis_kelamin</value>
      <webElementGuid>9cb6a20c-ae7e-4735-9198-b1adc5b44e07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                        -Pilih-
                                        LAKI-LAKI
                                        PEREMPUAN
                                      </value>
      <webElementGuid>b09e6286-3c24-4a87-aece-868047ad9000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jenis_kelamin&quot;)</value>
      <webElementGuid>22643bd9-e0ec-48b7-b79e-9cd7cee9b7d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='jenis_kelamin']</value>
      <webElementGuid>08c3b3c1-9569-4ba7-9b9c-65f5f521a5e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='default-wizard']/fieldset/div/div/div[6]/select</value>
      <webElementGuid>d9aa2718-1a86-4a5a-8d64-43c3a2ab8065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>f11b64b5-6d6c-45fe-9158-f3bc197694c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'jenis_kelamin' and @id = 'jenis_kelamin' and (text() = '
                                        -Pilih-
                                        LAKI-LAKI
                                        PEREMPUAN
                                      ' or . = '
                                        -Pilih-
                                        LAKI-LAKI
                                        PEREMPUAN
                                      ')]</value>
      <webElementGuid>e7ff3d67-7f68-4b51-b1be-ca9ba117bd82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
