<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-Pilih-                             _d2e932</name>
   <tag></tag>
   <elementGuidId>a46c8366-897b-4ab2-8f25-36b885e7307a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='status_kawin']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#status_kawin</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d64534d7-b14f-4b01-872d-4a66c480d493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>status_kawin</value>
      <webElementGuid>56b52d4f-8ae3-400f-b2d7-16d659904f0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8eaa355f-66b5-45e2-a503-7d31ff816276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>status_kawin</value>
      <webElementGuid>57fc7beb-d974-461e-ad5f-2e7a13292a9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                         -Pilih-
                                         KAWIN
                                         BELUM KAWIN
                                       </value>
      <webElementGuid>640b3f34-c394-4949-bc32-6994996935f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;status_kawin&quot;)</value>
      <webElementGuid>af31d67f-78f7-45f4-a55e-e6e0aa36c20b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='status_kawin']</value>
      <webElementGuid>3dbc7a28-662f-4efa-a18e-c0ef309903f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='default-wizard']/fieldset/div/div/div[8]/select</value>
      <webElementGuid>84153c0e-f4ed-4a2d-8c2f-f0fc09d46937</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/select</value>
      <webElementGuid>0b613a5d-a525-440e-a635-a7defb0aac7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'status_kawin' and @id = 'status_kawin' and (text() = '
                                         -Pilih-
                                         KAWIN
                                         BELUM KAWIN
                                       ' or . = '
                                         -Pilih-
                                         KAWIN
                                         BELUM KAWIN
                                       ')]</value>
      <webElementGuid>b3125f2f-cbe3-4fa6-b398-8ce824f3a8e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
