<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-Pilih-                             _cb70da</name>
   <tag></tag>
   <elementGuidId>9656aa2f-59c7-492a-9722-c88515b07d40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='golongan_darah']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#golongan_darah</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ea2829ad-c862-4a2d-9157-6273c88c1f12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>golongan_darah</value>
      <webElementGuid>6ef11d77-aba7-411c-a1ec-892fbd5c02bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>684599b7-6e13-4ea6-a87f-64c26674e9df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>golongan_darah</value>
      <webElementGuid>fb1f3e75-f447-4814-9c95-c5dd221ade83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                        -Pilih-
                                        A
                                        B
                                        AB
                                        O
                                      </value>
      <webElementGuid>fd367517-adb1-40d3-9bbd-85708cc54694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;golongan_darah&quot;)</value>
      <webElementGuid>cfd50cbe-fe5a-4b6f-bfe8-9629b6784f0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='golongan_darah']</value>
      <webElementGuid>bce6378f-8582-4858-8459-82d33a91d779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='default-wizard']/fieldset/div/div/div[7]/select</value>
      <webElementGuid>d3f939d3-213f-40c4-b98f-c6d88b4fcd73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/select</value>
      <webElementGuid>4ae8d745-3003-4e57-a86c-cf918949b3c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'golongan_darah' and @id = 'golongan_darah' and (text() = '
                                        -Pilih-
                                        A
                                        B
                                        AB
                                        O
                                      ' or . = '
                                        -Pilih-
                                        A
                                        B
                                        AB
                                        O
                                      ')]</value>
      <webElementGuid>3504e697-9b70-45cb-afcb-6606be36afce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
