<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_-----Pilih-----</name>
   <tag></tag>
   <elementGuidId>78529df5-dea9-4b3e-a32d-af223ab6156c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-kabupaten-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-kabupaten-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0ef7de96-d488-4ef7-aaa2-bdb54f50f23d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>10021a74-63fe-4217-a5ce-055faf67ee9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-kabupaten-container</value>
      <webElementGuid>65ba1282-41f8-4714-bfc0-03f04f498295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>-----Pilih-----</value>
      <webElementGuid>c569cc9b-4989-41f2-8e84-4601b1460020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-----Pilih-----</value>
      <webElementGuid>07c97a0a-79d4-401a-84e0-32ac0a3f980b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-kabupaten-container&quot;)</value>
      <webElementGuid>858c8d46-8509-4b78-96eb-9bf31a99b6e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-kabupaten-container']</value>
      <webElementGuid>a619e966-72ed-4c03-aca8-6c9a78df0f1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='default-wizard']/fieldset/div/div[2]/div[6]/span/span/span/span</value>
      <webElementGuid>42abd7ac-78f4-450d-8434-41958f5115c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/span/span/span/span</value>
      <webElementGuid>90da2187-63d2-4a8d-83d5-bfa369281190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-kabupaten-container' and @title = '-----Pilih-----' and (text() = '-----Pilih-----' or . = '-----Pilih-----')]</value>
      <webElementGuid>c456c5e7-c0ed-4a97-a8bc-28a5612d295e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
