<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_-- Pilih Lokasi Pekerjaan --</name>
   <tag></tag>
   <elementGuidId>0e3aef95-71ce-40c7-87cb-e905c8ea0c97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-lokasi_pekerjaan-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-lokasi_pekerjaan-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>942084b8-efd7-4376-a525-16d0449ed204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>3bc3a7cf-4d71-465e-8c4e-964746ff9851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-lokasi_pekerjaan-container</value>
      <webElementGuid>dbb360e3-a1dd-4cfa-a80a-c42a136c99ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>-- Pilih Lokasi Pekerjaan --</value>
      <webElementGuid>6071c63c-33fb-47ba-92f9-87996d3b1638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Pilih Lokasi Pekerjaan --</value>
      <webElementGuid>764d07d1-5638-4cf0-93c5-89de0b323437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-lokasi_pekerjaan-container&quot;)</value>
      <webElementGuid>1ae808e6-ea06-4e7f-a8f5-67f5dca29b22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-lokasi_pekerjaan-container']</value>
      <webElementGuid>867f7e3f-de83-426b-96cd-869628b25eae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='default-wizard']/fieldset/div/div/div[9]/span/span/span/span</value>
      <webElementGuid>ff168dc6-ccf5-4e85-95e2-e6f465e50a3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>e66f87df-ad4f-455e-9276-97d52b98846c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-lokasi_pekerjaan-container' and @title = '-- Pilih Lokasi Pekerjaan --' and (text() = '-- Pilih Lokasi Pekerjaan --' or . = '-- Pilih Lokasi Pekerjaan --')]</value>
      <webElementGuid>27ba265d-90ba-4487-9b3f-b2a6aebf9092</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
